### PR TITLE
Cleaned up websocket interface. Removed AssemblyInfo and moved versio…

### PR DESCRIPTION
**Pull request by benaclejames**
Cleaned up Websocket Interface. Moved assembly headers to MyCameraPlugin.cs. Moved main types to correct namespace. Fixed some fields and methods being declared as public, even though they're only used in the same class. Moved default settings txt info to an embedded resource for organisation. Enforced correct naming scheme for public, private, static, const and readonly fields.

### CODE REVIEW

**Comment by friesofdoom** [comment]
Wow, this looks pretty awesome (apart from GitHub completely butchering the diffs). Thank you!
I'll pull the code and test it locally sometime today.

**Comment by benaclejames** [comment]
Aha, Thanks! 😄
Just a heads up, I didn't test the http plugin integration very thoroughly but, logically speaking, there's no reason why it wouldn't work. Though like all code, it'll probably find a way to break so apologies if that's the case!

**Comment by friesofdoom** [comment]
Unfortunately there does seem to be a new bug in your changes, I just haven't had enough free time to sit down and figure out what the problem is. As soon as I do I should be able to merge the PR.

**Comment by benaclejames** [comment]
Oh, what's the bug?

**Pull request closed without merging**
